global:
  security:
    tls:
      enabled: true

eric-pm-server:
  enabled: true

eric-sec-sip-tls:
  enabled: true

eric-data-document-database-iam:
  enabled: true

eric-data-document-database-pg:
  enabled: true