{{ if .Values.global.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  labels:
  name: eric-dst-query-iccr-networkpolicy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-dst-query
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-tm-ingress-controller-cr
  policyTypes:
    - Ingress
{{- end }}
